spring:
  config:
    activate:
      on-profile: docker-compose
  rabbitmq:
    host: rabbitmq
  datasource:
    url: jdbc:postgresql://db:5432/compose-postgres
    username: compose-postgres
    password: compose-postgres