server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TaskManager_db
    username: root
    password: password_user
  redis:
    host: localhost
    port: 6379

rabbit:
  queue: EMAIL_SENDING_TASKS
  exchange: exchange
  routing-key: '#'
